-- This module serves as the root of the `Tests` library.
-- Import modules here that should be built as part of the library.
import Tests.Basic
import Tests.Ratio.Addition
import Tests.Ratio.Multiplication
import Tests.Ratio.Subtraction
import Tests.Ratio.Negation
import Tests.Ratio.Absolute
import Tests.Ratio.Reciprocal
import Tests.Ratio.IntegerRatio
import Tests.Ratio.RatioInteger
import Tests.Ratio.Misc
import Tests.Ratio.Ceil
import Tests.Ratio.Truncate

import Tests.Stablecoin.Theorem10
import Tests.Stablecoin.Theorem11
import Tests.Stablecoin.Theorem12
import Tests.Stablecoin.Theorem13_to_15
import Tests.Stablecoin.Theorem16
import Tests.Stablecoin.Theorem17
import Tests.Stablecoin.Theorem18
import Tests.Stablecoin.Theorem19
import Tests.Stablecoin.Theorem1_and_2
import Tests.Stablecoin.Theorem20
import Tests.Stablecoin.Theorem21_and_22
import Tests.Stablecoin.Theorem23_and_24
import Tests.Stablecoin.Theorem25_and_26
import Tests.Stablecoin.Theorem27_to_29
import Tests.Stablecoin.Theorem3
import Tests.Stablecoin.Theorem30_and_31
import Tests.Stablecoin.Theorem32_to_38
import Tests.Stablecoin.Theorem39_and_40
import Tests.Stablecoin.Theorem4
import Tests.Stablecoin.Theorem41
import Tests.Stablecoin.Theorem42
import Tests.Stablecoin.Theorem43
import Tests.Stablecoin.Theorem44_to_46
import Tests.Stablecoin.Theorem47
import Tests.Stablecoin.Theorem48
import Tests.Stablecoin.Theorem49_and_50
import Tests.Stablecoin.Theorem5
import Tests.Stablecoin.Theorem6
import Tests.Stablecoin.Theorem7
import Tests.Stablecoin.Theorem8
import Tests.Stablecoin.Theorem9
