name: ci-nix

permissions:
  contents: read

on:
  workflow_dispatch:

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Run flake checks
        run: nix flake check -L
